name: media_viewer
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  http: ^1.1.0
  cached_network_image: ^3.3.0
  photo_view: ^0.14.0
  pull_to_refresh_flutter3: ^2.0.2
  video_thumbnail: ^0.5.3
  path_provider: ^2.1.1
  video_player: ^2.7.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
